**Car Insurance Policies**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("Car_insurance_policies_data.xlsx")
df.head()

,ID,BirthDate,Car Color,Car Make,Car Model,Car Use,Car Year,Coverage Zone,Education,Gender,Marital Status,Parent,Claim Amount,Claim Freq,Household Income,Kids Driving
0,62-2999778,1965-08-09,Green,Acura,TSX,Private,2017,Highly Urban,High School,Male,Single,Yes,7375.988,1,220436.66,2
1,70-2426103,1991-04-21,Turquoise,Corbin,Sparrow,Private,2011,Urban,Bachelors,Female,Married,No,7897.541,1,66491.43,0
2,08-3808219,2002-03-08,Orange,Nissan,Pathfinder,Private,2000,Rural,Bachelors,Male,Divorced,No,3090.401,0,56122.70,0
3,38-0306843,1962-05-10,Pink,Ford,Econoline E350,Private,2007,Highly Urban,Bachelors,Female,Single,No,3025.782,1,175182.61,0
4,47-5163637,1995-01-15,Green,Nissan,350Z,Commercial,2013,Rural,Masters,Male,Single,No,5043.402,3,137110.23,0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37542 entries, 0 to 37541
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                37542 non-null  str
 1   BirthDate         37542 non-null  datetime64[us]
 2   Car Color         37542 non-null  str
 3   Car Make          37542 non-null  str
 4   Car Model         37542 non-null  object
 5   Car Use           37542 non-null  str
 6   Car Year          37542 non-null  int64
 7   Coverage Zone     37542 non-null  str
 8   Education         37542 non-null  str
 9   Gender            37542 non-null  str
 10  Marital Status    37542 non-null  str
 11  Parent            37542 non-null  str
 12  Claim Amount      37542 non-null  float64
 13  Claim Freq        37542 non-null  int64
 14  Household Income  37542 non-null  float64
 15  Kids Driving      37542 non-null  int64
dtypes: datetime64[us](1), float64(2), int64(3), object(1), str(9)
memory usage: 4.6+ MB

In [4]:
df.describe()

,BirthDate,Car Year,Claim Amount,Claim Freq,Household Income,Kids Driving
count,37542,37542.000000,37542.000000,37542.000000,37542.000000,37542.000000
mean,1979-05-07 10:05:32.555537,2007.293005,5002.851410,0.510308,147247.407750,0.418278
min,1952-10-21 00:00:00,1916.000000,0.004000,0.000000,45004.910000,0.000000
25%,1966-01-25 00:00:00,2002.000000,2543.940750,0.000000,96162.182500,0.000000
50%,1979-04-21 00:00:00,2009.000000,4945.589000,0.000000,146674.895000,0.000000
75%,1992-07-26 00:00:00,2014.000000,7497.492750,1.000000,198277.420000,1.000000
max,2005-10-18 00:00:00,2020.000000,9999.770000,4.000000,249991.110000,3.000000
std,NaN,9.045441,2870.651799,1.015050,59145.588886,0.736958

In [5]:
df.isnull().sum()

ID                  0
BirthDate           0
Car Color           0
Car Make            0
Car Model           0
Car Use             0
Car Year            0
Coverage Zone       0
Education           0
Gender              0
Marital Status      0
Parent              0
Claim Amount        0
Claim Freq          0
Household Income    0
Kids Driving        0
dtype: int64

In [6]:
col=df.columns
for i in col:
    print("----",i,"-----")
    print(df[i].unique())

---- ID -----
<StringArray>
['62-2999778', '70-2426103', '08-3808219', '38-0306843', '47-5163637',
 '07-4760971', '36-8207139', '57-6123340', '47-9063798', '92-8406214',
 ...
 '78-7827089', '35-8565336', '28-5914769', '53-3378094', '57-4483831',
 '97-1703438', '85-3811652', '77-2048493', '20-0183506', '01-2964308']
Length: 37541, dtype: str
---- BirthDate -----
<DatetimeArray>
['1965-08-09 00:00:00', '1991-04-21 00:00:00', '2002-03-08 00:00:00',
 '1962-05-10 00:00:00', '1995-01-15 00:00:00', '1966-11-06 00:00:00',
 '2002-08-27 00:00:00', '1983-02-26 00:00:00', '1953-10-06 00:00:00',
 '1995-12-18 00:00:00',
 ...
 '2003-07-16 00:00:00', '1980-06-25 00:00:00', '1985-03-06 00:00:00',
 '1995-06-20 00:00:00', '1979-08-11 00:00:00', '1991-03-30 00:00:00',
 '2001-02-20 00:00:00', '1966-10-08 00:00:00', '1988-08-06 00:00:00',
 '1962-05-16 00:00:00']
Length: 16517, dtype: datetime64[us]
---- Car Color -----
<StringArray>
[     'Green',  'Turquoise',     'Orange',       'Pink',     'Maroon',
     'Yellow',    'Crimson',  'Goldenrod',        'Red',     'Fuscia',
 'Aquamarine',       'Mauv',       'Blue',       'Teal',     'Indigo',
       'Puce',     'Violet',     'Purple',      'Khaki']
Length: 19, dtype: str
---- Car Make -----
<StringArray>
[        'Acura',        'Corbin',        'Nissan',          'Ford',
 'Mercedes-Benz',        'Toyota',       'Lincoln',         'Mazda',
     'Chevrolet',         'Eagle',    'Oldsmobile',         'Volvo',
        'Suzuki',       'Porsche',      'Infiniti',        'Subaru',
           'GMC',           'BMW',      'Chrysler',         'Dodge',
         'Honda',    'Volkswagen',          'MINI',         'Lexus',
           'Kia',          'Audi',       'Pontiac',       'Bentley',
          'Saab',        'Merkur',          'Jeep',        'Austin',
         'Buick',        'Hummer',   'Lamborghini',    'Mitsubishi',
       'Mercury',      'Cadillac',         'Isuzu',        'Saturn',
         'Lotus',       'Hyundai',   'Rolls-Royce',         'Scion',
        'Daewoo',      'Plymouth',        'Jaguar',    'Land Rover',
        'Holden',       'Rambler',       'Ferrari',        'Spyker',
  'Aston Martin',      'Maserati',    'Alfa Romeo',         'Smart',
           'Ram',        'Aptera',          'Fiat',      'Daihatsu',
       'Maybach',        'Morgan',       'McLaren',       'Peugeot',
       'Hillman',         'Foose',           'Geo',         'Panoz',
        'Jensen',    'Studebaker',       'Citroën',         'Tesla',
            'MG',        'Shelby',       'Bugatti',      'Fillmore',
       'Renault',    'Fairthorpe']
Length: 78, dtype: str
---- Car Model -----
['TSX' 'Sparrow' 'Pathfinder' ... 'Sixty Special' 'Silverado Hybrid'
 'W123']
---- Car Use -----
<StringArray>
['Private', 'Commercial']
Length: 2, dtype: str
---- Car Year -----
[2017 2011 2000 2007 2013 2006 1996 2002 2001 2003 2004 1999 2015 2010
 2016 2018 1992 2019 2012 2005 1980 1986 2020 2008 1995 1998 1994 1966
 1997 1979 2014 2009 1993 1987 1972 1991 1990 1984 1970 1975 1974 1981
 1971 1976 1983 1985 1977 1962 1988 1964 1982 1973 1978 1957 1989 1969
 1967 1916 1955 1961 1965 1968 1933 1963]
---- Coverage Zone -----
<StringArray>
['Highly Urban', 'Urban', 'Rural', 'Highly Rural', 'Suburban']
Length: 5, dtype: str
---- Education -----
<StringArray>
['High School', 'Bachelors', 'Masters', 'PhD']
Length: 4, dtype: str
---- Gender -----
<StringArray>
['Male', 'Female']
Length: 2, dtype: str
---- Marital Status -----
<StringArray>
['Single', 'Married', 'Divorced', 'Seperated']
Length: 4, dtype: str
---- Parent -----
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
---- Claim Amount -----
[7375.988 7897.541 3090.401 ... 7434.861 5357.388 3403.647]
---- Claim Freq -----
[1 0 3 2 4]
---- Household Income -----
[220436.66  66491.43  56122.7  ... 126394.18  58673.19  95506.43]
---- Kids Driving -----
[2 0 1 3]

In [7]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
37537    False
37538    False
37539    False
37540    False
37541    False
Length: 37542, dtype: bool

In [8]:
df.to_csv("Clean_Car_Insurance_Policy.csv")